### ISSUE TITLE
Nothing happens when I click on "Yes please" or "Nope" on Messenger

### ISSUE THREAD

**Issue by andreshg112** [christophrumpel/bcwp-laraconeu-chatbot#3]
"Hi" and "Start conversation" work. FAQs don't work, neither GET_STARTED does. Telegram still works (see the last image).

![image](https://user-images.githubusercontent.com/15859884/44323065-e5b65380-a415-11e8-8970-ea00c562236b.png)
----------
![image](https://user-images.githubusercontent.com/15859884/44323104-0d0d2080-a416-11e8-9df0-c1829f8e873e.png)
----------
![image](https://user-images.githubusercontent.com/15859884/44323097-08e10300-a416-11e8-8bc5-d37ef18ee0ee.png)

If I enable message_postbacks, my server receives a request. However, nothing happens.

![image](https://user-images.githubusercontent.com/15859884/44323171-5a898d80-a416-11e8-823e-7356d75bdf40.png)
----------
![image](https://user-images.githubusercontent.com/15859884/44323218-902e7680-a416-11e8-821c-facb981e60b3.png)

It's still working with Telegram.
![image](https://user-images.githubusercontent.com/15859884/44323412-80636200-a417-11e8-9224-982bf983b060.png)

**Comment by christophrumpel** [comment]
Hey, for both Telegram and Facebook you have `activate` the GET STARTED function. Have you done that like mentioned in the book?

**Comment by andreshg112** [comment]
I think I did it.

# Telegram:
![image](https://user-images.githubusercontent.com/15859884/44376145-b9a1dd80-a4bc-11e8-9c0a-fb63326ae55b.png)

# Facebook:
![image](https://user-images.githubusercontent.com/15859884/44376171-d63e1580-a4bc-11e8-9fbc-36b5ed313777.png)
If a click on Get started, ngrok doesn't detect anything.

And I did this:
`php artisan botman:facebookAddStartButton`

**Comment by andreshg112** [comment]
If I type in on Facebook GET_STARTED or /start, It works.
But now I clicked on Yes please for subscribing me, and I receive a lot of requests.
# Chat
![image](https://user-images.githubusercontent.com/15859884/44380008-6f295c80-a4ce-11e8-9680-12d37eae434a.png)


# ngrok
![image](https://user-images.githubusercontent.com/15859884/44380027-87997700-a4ce-11e8-8001-2153ca2ba464.png)

**Comment by christophrumpel** [comment]
So you mean typing `GET_STARTED` or `/'start` works but clicking the buttons that Telegram and Facebook provide?

**Comment by andreshg112** [comment]
Everything works perfectly in Telegram. On Facebook, GET_STARTED was not working, and Facebook was sending me a lot of requests that my server didn't answer. https://github.com/christophrumpel/bcwp-laraconeu-chatbot/issues/3#issuecomment-414544164

**Comment by andreshg112** [comment]
I restarted the server and set up everything again. I'm getting the same error when I click on "Yes please".
After clicking on "yes please", It stops working on Facebook.
![image](https://user-images.githubusercontent.com/15859884/44427491-5913ae80-a557-11e8-9b90-b46e6ff5eef2.png)

After some minutes I'm still receiving the request "Yes please" from Facebook.
![image](https://user-images.githubusercontent.com/15859884/44427753-07b7ef00-a558-11e8-8075-23fed8fe7dcd.png)

It's still working on Telegram.
![image](https://user-images.githubusercontent.com/15859884/44427670-d5a68d00-a557-11e8-97b6-cfe1743c7aec.png)

**Comment by andreshg112** [comment]
Do I have to enable this? What is this for?
![image](https://user-images.githubusercontent.com/15859884/44427891-6715ff00-a558-11e8-9251-59f672b4884d.png)

**Comment by andreshg112** [comment]
I have to click on Unsubscribe in order to stop receiving requests from Facebook.
![image](https://user-images.githubusercontent.com/15859884/44430278-d5aa8b00-a55f-11e8-9004-2b908741f282.png)

Now, I noticed something strange.

This is my code. Notice that I put some echo lines.
```php
<?php

namespace App\Http\Conversations;

use App\Subscriber;
use BotMan\BotMan\Messages\Conversations\Conversation;
use BotMan\BotMan\Messages\Incoming\Answer;
use BotMan\BotMan\Messages\Outgoing\Actions\Button;
use BotMan\BotMan\Messages\Outgoing\Question;

class OnboardingConversation extends Conversation
{
    /**
     * Start the conversation.
     *
     * @return mixed
     */
    public function run()
    {
        $this->welcomeUser();
    }

    private function welcomeUser()
    {
        $this->say('Welcome! This is the Laracon EU chatbot.');
        $this->say(
            'I can provide you with info about the Laracon EU conference. You can ask me about speakers, the schedule, or sponsors.'
        );
        $this->askAboutNotifications();
    }

    private function askAboutNotifications()
    {
        $question = Question::create(
            'I am also able to send you important notifications about new speakers or schedule changes during the conference. To make that possible I need to store your chat ID and your first name. Are you fine with that? (You can change your answer at any time.)'
        )->addButtons([
            Button::create('Yes please')->value('yes'),
            Button::create('Nope')->value('no'),
        ]);

        $this->ask($question, function (Answer $answer) {
            echo json_encode($answer) . "\n";
            echo $answer->getText() . "\n";
            switch ($answer->getText()) {
                case 'no':
                    echo "no way";
                    Subscriber::deleteUserIfGiven($this->bot->getUser()->getId());
                    $this->say('Ok, no problem.');

                    return $this->showGeneralInfo();
                case 'yes':
                    echo "yes way";
                    Subscriber::storeFromBotManUser(
                        $this->bot->getDriver()->getName(),
                        $this->bot->getUser()
                    );
                    $this->say('Perfect.');

                    return $this->showGeneralInfo();
                default:
                    echo "default way";
                    $this->say('I am not sure what you meant. Can you try again?');
                    return $this->repeat();
            }
        });
    }

    private function showGeneralInfo()
    {
        return $this->say("These are some example sentences that you can use:\n
        - \"Show me the speakers.\"
        - \"Who is sponsoring this year?\"
        ");
    }
}
```

Look this: If I type in "Hi", I get the default message. You can see that the server answers with:
```
{}
Hi
default way
```
![image](https://user-images.githubusercontent.com/15859884/44430255-c0cdf780-a55f-11e8-89b1-5d3d1cbd48be.png)

This is what I get on ngrok if I type in "Hi".
![image](https://user-images.githubusercontent.com/15859884/44430709-240c5980-a561-11e8-9609-e1453656a8b8.png)

If I click on "Yes please" or "Nope", nothing happens:
![image](https://user-images.githubusercontent.com/15859884/44430739-3c7c7400-a561-11e8-96bb-e8ef7c008dcc.png)

This is what I get clicking on "yes" or "no". You can't see the result from `echo "no way";` or `echo "yes way";`
![image](https://user-images.githubusercontent.com/15859884/44430758-50c07100-a561-11e8-8a1a-ecca2198c722.png)

Everything still works perfectly on Telegram.

**Comment by andreshg112** [comment]
I just noticed something:
If I comment the database call, It works:
![image](https://user-images.githubusercontent.com/15859884/44442442-db23c780-a597-11e8-9029-b15f95b5f61f.png)

**Comment by andreshg112** [comment]
I just saw laravel.log:
```
[2018-08-22 04:56:12] local.ERROR: Error sending payload: (#100) Insufficient permission to access user profile. {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: (#100) Insufficient permission to access user profile. at /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/botman/driver-facebook/src/FacebookDriver.php:503)
[stacktrace]
#0 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/botman/driver-facebook/src/FacebookDriver.php(460): BotMan\\Drivers\\Facebook\\FacebookDriver->throwExceptionIfResponseNotOk(Object(Symfony\\Component\\HttpFoundation\\Response))
#1 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/botman/botman/src/BotMan.php(236): BotMan\\Drivers\\Facebook\\FacebookDriver->getUser(Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage))
#2 closure://function (\\BotMan\\BotMan\\Messages\\Incoming\\Answer $answer) {
            switch ($answer->getText()) {
                case 'no':
                    \\App\\Subscriber::deleteUserIfGiven($this->bot->getUser()->getId());
                    $this->say('Ok, no problem.');

                    return $this->showGeneralInfo();
                case 'yes':
                    \\App\\Subscriber::storeFromBotManUser(
                        $this->bot->getDriver()->getName(),
                        $this->bot->getUser()
                    );
                    $this->say('Perfect.');

                    return $this->showGeneralInfo();
                default:
                    $this->say('I am not sure what you meant. Can you try again?');
                    return $this->repeat();
            }
        }(12): BotMan\\BotMan\\BotMan->getUser()
#3 [internal function]: App\\Http\\Conversations\\OnboardingConversation->{closure}(Object(BotMan\\BotMan\\Messages\\Incoming\\Answer), Object(App\\Http\\Conversations\\OnboardingConversation))
#4 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/botman/botman/src/Traits/HandlesConversations.php(293): call_user_func_array(Object(Closure), Array)
#5 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/botman/botman/src/Traits/HandlesConversations.php(271): BotMan\\BotMan\\BotMan->prepareConversationClosure(Object(Closure), Object(App\\Http\\Conversations\\OnboardingConversation), Array)
#6 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/botman/botman/src/Traits/HandlesConversations.php(233): BotMan\\BotMan\\BotMan->callConversation(Object(Opis\\Closure\\SerializableClosure), Array, Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage), Array)
#7 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Support/Collection.php(397): BotMan\\BotMan\\BotMan->BotMan\\BotMan\\Traits\\{closure}(Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage), 0)
#8 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/botman/botman/src/Traits/HandlesConversations.php(235): Illuminate\\Support\\Collection->each(Object(Closure))
#9 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/botman/botman/src/BotMan.php(405): BotMan\\BotMan\\BotMan->loadActiveConversation()
#10 /opt/lampp/htdocs/book-laraconeu-chatbot/app/Http/Controllers/BotManController.php(18): BotMan\\BotMan\\BotMan->listen()
#11 [internal function]: App\\Http\\Controllers\\BotManController->handle()
#12 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#13 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handle', Array)
#14 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\BotManController), 'handle')
#15 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#16 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#17 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#39 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#40 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#41 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#42 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#43 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#60 /opt/lampp/htdocs/book-laraconeu-chatbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#61 /opt/lampp/htdocs/book-laraconeu-chatbot/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#62 {main}
"} 
```

**Comment by andreshg112** [comment]
Solved by using `getUserWithFields()` when Facebook is the driver:
```php
private function askAboutNotifications()
    {
        $question = Question::create(
            'I am also able to send you important notifications about new speakers or schedule changes during the conference. To make that possible I need to store your chat ID and your first name. Are you fine with that? (You can change your answer at any time.)'
        )->addButtons([
            Button::create('Yes please')->value('yes'),
            Button::create('Nope')->value('no'),
        ]);

        $this->ask($question, function (Answer $answer) {
            switch ($answer->getText()) {
                case 'no':
                    $user = $this->getUser();
                    Subscriber::deleteUserIfGiven($user->getId());
                    $this->say('Ok, no problem.');

                    return $this->showGeneralInfo();
                case 'yes':
                    $user = $this->getUser();
                    Subscriber::storeFromBotManUser(
                        $this->bot->getDriver()->getName(),
                        $user
                    );
                    $this->say('Perfect.');

                    return $this->showGeneralInfo();
                default:
                    $this->say('I am not sure what you meant. Can you try again?');
                    return $this->repeat();
            }
        });
    }

    /**
     * Returns the user depending the driver.
     *
     * @return \BotMan\BotMan\Users\User
     */
    private function getUser() : User
    {
        $driverName = $this->bot->getDriver()->getName();
        switch ($driverName) {
            case 'Facebook':
                $user = $this->bot->getUserWithFields([
                    'id', 'name', 'first_name', 'last_name', 'profile_pic'
                ]);
                break;
            default:
                $user = $this->bot->getUser();
                break;
        }
        return $user;
    }
```

**Comment by christophrumpel** [comment]
@andreshg112 great you solved it. There was a change with FB and this is why you need the new method now. I think we will change it in BotMan so we can use the normal method again. Waiting for a decision here. Then Ill update the book.
